= Md Azhar - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: VetterAppointments

== Overview

VetterAppointments is a desktop application used for managing a vet's clients, pets, appointments and staff. +

VetterAppointments aims to simplify the process of scheduling an appointment as well as managing the
people and animals under a vet. It does this by removing the clutter in traditional scheduling applications. +

The user interacts with the program through a Command Line Interface (CLI) via inputting commands. These
feature is supported by a beautifully crafted Graphical User Interface (GUI). Everything that can be done
by the commands can also be done by the mouse. +

VetterAppointments' GUI is built using JavaFX. The program is written in Java and has about 20kLoc.

== Summary of contributions

* *Major Enhancement*: A collection of commands that supports the Pet component and Appointment component.

. Pet class containing: PetName, PetAge, PetGender and Tag classes.
. AddPetCommand
. DeletePetCommand
. AddAppointmentToPetCommand
. RemoveAppointmentFromPetCommand
. SortAppointmentCommand
. SortClientCommand
. SortPetCommand
. UnscheduleCommand

** Justification: +
The enhancements play a major role in VetterAppointments. It serves as the backbone in terms of adding
the required components so that the user can manage them. The features adds an important class to a program
targeted at vets, which are pets.

** Highlights: +
The design consideration when adding a major components was thoroughly thought-out. The components are
independent and are not coupled. A wrapper class was introduced to mark an association between a pet
and its owner. This will then be fed into an appointment object, which is the overheading class.

* *Minor Enhancements*: Adding command aliases so that commands will not be too lengthy for the user
to type. Several components and command features are classified as incremental minor enhancements.

* *Code Contribution*: +
** [https://github.com/CS2103JAN2018-F09-B4/main/blob/master/collated/functional/md-azsa.md[Functional code]]
 [https://github.com/CS2103JAN2018-F09-B4/main/blob/master/collated/test/md-azsa.md[Test code]]

* *Other contributions:* +
** Project management:
*** Managed the releases of `v1.4` & `v1.5` on GitHub
** Documentation:
*** Added most of the materials in README and UserGuide (screenshots, landing page logo and output images).
*** Managed the formatting for UserGuide to ensure consistency in format and language.
*** Added user stories for Developer Guide.
** Community:
*** Reported and documented bugs for other teams in procedural manner: +
https://github.com/CS2103JAN2018-T09-B4/main/issues/144[#144],
https://github.com/CS2103JAN2018-T09-B4/main/issues/145[#145],
https://github.com/CS2103JAN2018-T09-B4/main/issues/149[#149],
https://github.com/CS2103JAN2018-T09-B4/main/issues/152[#152]
*** Reported bugs and provided solutions to team: +
https://github.com/CS2103JAN2018-F09-B4/main/issues/239[#239],
https://github.com/CS2103JAN2018-F09-B4/main/issues/207[#207]

== Contributions to userguide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=userInterfaceWalkthrough]
include::../UserGuide.adoc[tag=addPetCommand]
include::../UserGuide.adoc[tag=addAppointmentToPetCommand]
include::../UserGuide.adoc[tag=deletePetCommand]
include::../UserGuide.adoc[tag=unscheduleCommand]
include::../UserGuide.adoc[tag=removeAppointmentFromPetCommand]
include::../UserGuide.adoc[tag=sortpCommand]
include::../UserGuide.adoc[tag=commandSummaryTable]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=mdazharEnhancements]
include::../DeveloperGuide.adoc[tag=mdazharPet]


